---
extends: default

rules:
  comments:
    min-spaces-from-content: 1

  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  truthy:
    check-keys: false
